name: MonsterFix
main: fromgate.mccity.monsterfix.MonsterFix
version: 0.3.0
author: fromgate, fromgate@gmail.com
commands:
   mfix:
      description: MonsterFix configuration command
      usage: |
           /mfix help